### ISSUE TITLE
Icon Request: Filter

### ISSUE THREAD

**Issue by cnhymer** [indiana-university/rivet-icons#42]
![image](https://user-images.githubusercontent.com/47367585/61394642-98469e80-a891-11e9-9e69-252a5359fb12.png)

I've been doing a lot of work that could use an icon for "filter" and just learned that multiple people in ES have created their own filter icons too (one example seen in the screenshot)

**Comment by cwthomps** [comment]
I've created this, and will try and get it into the src soon.

**Comment by illusivesunrae** [comment]
@cwthomps Have you had a chance to add this?

**Comment by cwthomps** [comment]
@illusivesunrae Here's the SVG. It's been a while since I added an icon to the library, so hoping someone can help with that.

`<svg width="16" height="15" viewBox="0 0 16 15" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
<path fill-rule="evenodd" clip-rule="evenodd" d="M0.110836 0.542418C0.28224 0.209347 0.625416 0 1 0H15C15.3746 0 15.7178 0.209347 15.8892 0.542418C16.0606 0.87549 16.0315 1.27642 15.8137 1.58124L11 8.32047V12C11 12.3788 10.786 12.725 10.4472 12.8944L6.44722 14.8944C6.13723 15.0494 5.76909 15.0329 5.47427 14.8507C5.17946 14.6684 5 14.3466 5 14V8.32047L0.18627 1.58124C-0.0314543 1.27642 -0.0605684 0.87549 0.110836 0.542418ZM2.94319 2L7 7.67953V12.382L9 11.382V7.67953L13.0568 2H2.94319Z" fill="currentColor"/>
</svg>
`

**Comment by illusivesunrae** [comment]
Thanks, @cwthomps! @levimcg, would you be able to do this or remind @zttodd and I how to do this (we can then update the documentation if that's the case)?

**Comment by levimcg** [comment]
Yep. I think it would be good to go through that process with @zttodd since he hasn't had a chance to work on the icon library at all. I'll schedule something so we can go over it in person.

**Comment by illusivesunrae** [comment]
Awesome! Thanks, @levimcg! 🙌

**Comment by levimcg** [comment]
New filter icon was added via #43 and is now available. See #44 for more info.
