### ISSUE TITLE
SVG icons do not work in Internet Explorer

### ISSUE THREAD

**Issue by UIDvlpr** [indiana-university/rivet-icons#63]
## Describe the bug
Rivet icons do not show up in IE11. Open https://indiana-university.github.io/rivet-icons/ in IE11. Will this be remedied in Rivet 2.x? 

## Expected behavior
These should show up in all browsers.

## Relevant context (required)
- If applicable, add screenshots to help explain your problem.
![Icons-not-working](https://user-images.githubusercontent.com/37874411/84425907-5d0f3580-abf0-11ea-8ac6-1a76262b254b.png)
![Icons-working-in-Chromium-Based-Edge](https://user-images.githubusercontent.com/37874411/84425913-5e406280-abf0-11ea-9e57-4308ac80bad4.png)
![IUSM-Icons-not-working](https://user-images.githubusercontent.com/37874411/84425918-600a2600-abf0-11ea-8bd6-f22135e8c8cf.png)

## Steps to reproduce
1. Open IE11
2. Go to https://medicine.iu.edu or https://indiana-university.github.io/rivet-icons/
3. The icons do not appear

**Comment by levimcg** [comment]
@UIDvlpr Thanks for opening this issue. I've transferred it from the main `rivet-source` repo. We maintain the icons a separate repository here.

If you want to use the SVG as a symbol with the `<use xlink:href="/FrontEnd/Images/rvt-icons.svg#rvt-icon-chevron-right"></use>` syntax in IE11 you'll need to include a small JavaScript polyfill. There's a link and documentation here in the README for the icons about how to do that.

https://github.com/indiana-university/rivet-icons#usage

Otherwise you can inline the SVG directly in your template/markup.

**Comment by levimcg** [comment]
Linked to instructions on using IE 11 polyfill on 06/12/2020.
